version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 test_any.wsgi
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      shm_size: 2g
    shm_size: 2g
    # build: ./celery-queue
    command: celery -A test_any worker --loglevel=info
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: "redis:alpine"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
  # monitor:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.prod
  #   command: celery flower --broker=redis://redis:6379/0 --port=5555
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #   env_file:
  #     - ./.env.prod
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
